// frontend/admin-ui/src/components/Form.tsx
import React from 'react';
import { FormInput, FormInputData } from './FormInput';
import { useForm } from 'react-hook-form';

export interface FormData {
    fields: FormInputData[],
    changeValue: (value: string | File | null, index: number) => void,
    submit: (event: any) => void,
}

export const Form = (props: FormData): JSX.Element => {

    const { register, handleSubmit } = useForm();
    const onSubmit = handleSubmit((data) => props.submit(data));

    return (
        <form className="form" onSubmit={onSubmit} >
            {props.fields.map((input, index) => {
                return (
                    <FormInput register={register} key={index} type={input.type} name={input.name} placeholder={input.placeholder} index={index} selects={input.selects ? input.selects : undefined} />
                )
            })}
            <input type="submit" />
        </form>
    )
}

// frontend/client-ui/src/components/Form.vue
<template>
  <div class="flex-vertical">
    <form class="flex-vertical centered" @submit.prevent="handleSubmit">
      <FormInput
        v-for="(input, index) in value"
        :key="index"
        :inputType="input.inputType"
        :placeholder="input.placeholder"
        :value="input.value"
        :index="index"
        :height="input.height"
        @changeValue="onValueChange"
      />
      <FormInput inputType="submit" />
    </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import FormInput, { InputObject } from "@/components/FormInput.vue";

@Component({
  name: "Form",
  components: {
    FormInput,
  },
})
export default class Form extends Vue {
  @Prop() value!: InputObject[];

  private onValueChange(inputValue: string | File, index: number): void {
    this.value[index].value = inputValue;
  }

  private handleSubmit(): void {
    this.$emit("handleFormSubmit", this.value);
  }
}
</script>

<style lang="scss" scoped>
form {
  width: 60vw;
}
</style>
